'use strict';var _self="undefined"!=typeof window?window:"undefined"!=typeof WorkerGlobalScope&&self instanceof WorkerGlobalScope?self:{},Prism=function(h){function r(g,n,t,k){this.type=g;this.content=n;this.alias=t;this.length=0|(k||"").length}function l(g,n,t,k){g.lastIndex=n;(g=g.exec(t))&&k&&g[1]&&(k=g[1].length,g.index+=k,g[0]=g[0].slice(k));return g}function f(g,n,t,k,q,u){for(var w in t)if(t.hasOwnProperty(w)&&t[w]){var A=t[w];A=Array.isArray(A)?A:[A];for(var x=0;x<A.length;++x){if(u&&u.cause==
w+","+x)return;var y=A[x],z=y.inside,D=!!y.lookbehind,G=!!y.greedy,J=y.alias;if(G&&!y.pattern.global){var B=y.pattern.toString().match(/[imsuy]*$/)[0];y.pattern=RegExp(y.pattern.source,B+"g")}y=y.pattern||y;B=k.next;for(var E=q;B!==n.tail&&!(u&&E>=u.reach);E+=B.value.length,B=B.next){var C=B.value;if(n.length>g.length)return;if(!(C instanceof r)){var H,F=1;if(G){if(!(H=l(y,E,g,D))||H.index>=g.length)break;var I=H.index,L=H.index+H[0].length;C=E;for(C+=B.value.length;I>=C;)C+=(B=B.next).value.length;
if(E=C-=B.value.length,B.value instanceof r)continue;for(I=B;I!==n.tail&&(C<L||"string"==typeof I.value);I=I.next)F++,C+=I.value.length;F--;C=g.slice(E,C);H.index-=E}else if(!(H=l(y,0,C,D)))continue;I=H.index;L=H[0];var K=C.slice(0,I);I=C.slice(I+L.length);C=E+C.length;u&&C>u.reach&&(u.reach=C);var N=B.prev;K&&(N=a(n,N,K),E+=K.length);K=n;for(var O=N,M=O.next,P=0;P<F&&M!==K.tail;P++)M=M.next;O.next=M;M.prev=O;K.length-=P;if(B=a(n,N,new r(w,z?d.tokenize(L,z):L,J,L)),I&&a(n,B,I),F>1)F={cause:w+","+
x,reach:C},f(g,n,t,B.prev,E,F),u&&F.reach>u.reach&&(u.reach=F.reach)}}}}}function b(){var g={value:null,prev:null,next:null},n={value:null,prev:g,next:null};g.next=n;this.head=g;this.tail=n;this.length=0}function a(g,n,t){var k=n.next;t={value:t,prev:n,next:k};return n.next=t,k.prev=t,g.length++,t}function c(){d.manual||d.highlightAll()}var e=/(?:^|\s)lang(?:uage)?-([\w-]+)(?=\s|$)/i,m=0,p={},d={manual:h.Prism&&h.Prism.manual,disableWorkerMessageHandler:h.Prism&&h.Prism.disableWorkerMessageHandler,
util:{encode:function t(n){return n instanceof r?new r(n.type,t(n.content),n.alias):Array.isArray(n)?n.map(t):n.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/\u00a0/g," ")},type:function(n){return Object.prototype.toString.call(n).slice(8,-1)},objId:function(n){return n.__id||Object.defineProperty(n,"__id",{value:++m}),n.__id},clone:function q(t,k){var u,w;switch(k=k||{},d.util.type(t)){case "Object":if(w=d.util.objId(t),k[w])return k[w];for(var A in u={},k[w]=u,t)t.hasOwnProperty(A)&&(u[A]=
q(t[A],k));return u;case "Array":return w=d.util.objId(t),k[w]?k[w]:(u=[],k[w]=u,t.forEach(function(x,y){u[y]=q(x,k)}),u);default:return t}},getLanguage:function(t){for(;t;){var k=e.exec(t.className);if(k)return k[1].toLowerCase();t=t.parentElement}return"none"},setLanguage:function(t,k){t.className=t.className.replace(RegExp(e,"gi"),"");t.classList.add("language-"+k)},currentScript:function(){if("undefined"==typeof document)return null;if("currentScript"in document)return document.currentScript;
try{throw Error();}catch(u){var t=(/at [^(\r\n]*\((.*):[^:]+:[^:]+\)$/i.exec(u.stack)||[])[1];if(t){var k=document.getElementsByTagName("script"),q;for(q in k)if(k[q].src==t)return k[q]}return null}},isActive:function(t,k,q){for(var u="no-"+k;t;){var w=t.classList;if(w.contains(k))return!0;if(w.contains(u))return!1;t=t.parentElement}return!!q}},languages:{plain:p,plaintext:p,text:p,txt:p,extend:function(t,k){t=d.util.clone(d.languages[t]);for(var q in k)t[q]=k[q];return t},insertBefore:function(t,
k,q,u){var w=(u=u||d.languages)[t],A={},x;for(x in w)if(w.hasOwnProperty(x)){if(x==k)for(var y in q)q.hasOwnProperty(y)&&(A[y]=q[y]);q.hasOwnProperty(x)||(A[x]=w[x])}var z=u[t];return u[t]=A,d.languages.DFS(d.languages,function(D,G){G===z&&D!=t&&(this[D]=A)}),A},DFS:function A(k,q,u,w){w=w||{};var x=d.util.objId,y;for(y in k)if(k.hasOwnProperty(y)){q.call(k,y,k[y],u||y);var z=k[y],D=d.util.type(z);"Object"!==D||w[x(z)]?"Array"!==D||w[x(z)]||(w[x(z)]=!0,A(z,q,y,w)):(w[x(z)]=!0,A(z,q,null,w))}}},plugins:{},
highlightAll:function(k,q){d.highlightAllUnder(document,k,q)},highlightAllUnder:function(k,q,u){k={callback:u,container:k,selector:'code[class*="language-"], [class*="language-"] code, code[class*="lang-"], [class*="lang-"] code'};d.hooks.run("before-highlightall",k);k.elements=Array.prototype.slice.apply(k.container.querySelectorAll(k.selector));d.hooks.run("before-all-elements-highlight",k);for(var w=0;u=k.elements[w++];)d.highlightElement(u,!0===q,k.callback)},highlightElement:function(k,q,u){function w(D){z.highlightedCode=
D;d.hooks.run("before-insert",z);z.element.innerHTML=z.highlightedCode;d.hooks.run("after-highlight",z);d.hooks.run("complete",z);u&&u.call(z.element)}var A=d.util.getLanguage(k),x=d.languages[A];d.util.setLanguage(k,A);var y=k.parentElement;y&&"pre"===y.nodeName.toLowerCase()&&d.util.setLanguage(y,A);var z={element:k,language:A,grammar:x,code:k.textContent};if(d.hooks.run("before-sanity-check",z),(y=z.element.parentElement)&&"pre"===y.nodeName.toLowerCase()&&!y.hasAttribute("tabindex")&&y.setAttribute("tabindex",
"0"),!z.code)return d.hooks.run("complete",z),void(u&&u.call(z.element));(d.hooks.run("before-highlight",z),z.grammar)?q&&h.Worker?(k=new Worker(d.filename),k.onmessage=function(D){w(D.data)},k.postMessage(JSON.stringify({language:z.language,code:z.code,immediateClose:!0}))):w(d.highlight(z.code,z.grammar,z.language)):w(d.util.encode(z.code))},highlight:function(k,q,u){k={code:k,grammar:q,language:u};if(d.hooks.run("before-tokenize",k),!k.grammar)throw Error('The language "'+k.language+'" has no grammar.');
return k.tokens=d.tokenize(k.code,k.grammar),d.hooks.run("after-tokenize",k),r.stringify(d.util.encode(k.tokens),k.language)},tokenize:function(k,q){var u=q.rest;if(u){for(var w in u)q[w]=u[w];delete q.rest}u=new b;a(u,u.head,k);f(k,u,q,u.head,0);k=[];for(q=u.head.next;q!==u.tail;)k.push(q.value),q=q.next;return k},hooks:{all:{},add:function(k,q){var u=d.hooks.all;u[k]=u[k]||[];u[k].push(q)},run:function(k,q){if((k=d.hooks.all[k])&&k.length)for(var u,w=0;u=k[w++];)u(q)}},Token:r};if(h.Prism=d,r.stringify=
function w(q,u){if("string"==typeof q)return q;if(Array.isArray(q)){var A="";return q.forEach(function(z){A+=w(z,u)}),A}var x={type:q.type,content:w(q.content,u),tag:"span",classes:["token",q.type],attributes:{},language:u};(q=q.alias)&&(Array.isArray(q)?Array.prototype.push.apply(x.classes,q):x.classes.push(q));d.hooks.run("wrap",x);q="";for(var y in x.attributes)q+=" "+y+'="'+(x.attributes[y]||"").replace(/"/g,"&quot;")+'"';return"<"+x.tag+' class="'+x.classes.join(" ")+'"'+q+">"+x.content+"</"+
x.tag+">"},!h.document)return h.addEventListener?(d.disableWorkerMessageHandler||h.addEventListener("message",function(q){q=JSON.parse(q.data);var u=q.language,w=q.immediateClose;h.postMessage(d.highlight(q.code,d.languages[u],u));w&&h.close()},!1),d):d;p=d.util.currentScript();if(p&&(d.filename=p.src,p.hasAttribute("data-manual")&&(d.manual=!0)),!d.manual){var v=document.readyState;"loading"===v||"interactive"===v&&p&&p.defer?document.addEventListener("DOMContentLoaded",c):window.requestAnimationFrame?
window.requestAnimationFrame(c):window.setTimeout(c,16)}return d}(_self);"undefined"!=typeof module&&module.exports&&(module.exports=Prism);"undefined"!=typeof global&&(global.Prism=Prism);
!function(h){var r=/(?:"(?:\\(?:\r\n|[\s\S])|[^"\\\r\n])*"|'(?:\\(?:\r\n|[\s\S])|[^'\\\r\n])*')/;h.languages.css={comment:/\/\*[\s\S]*?\*\//,atrule:{pattern:RegExp("@[\\w-](?:[^;{\\s\"']|\\s+(?!\\s)|"+r.source+")*?(?:;|(?=\\s*\\{))"),inside:{rule:/^@[\w-]+/,"selector-function-argument":{pattern:/(\bselector\s*\(\s*(?![\s)]))(?:[^()\s]|\s+(?![\s)])|\((?:[^()]|\([^()]*\))*\))+(?=\s*\))/,lookbehind:!0,alias:"selector"},keyword:{pattern:/(^|[^\w-])(?:and|not|only|or)(?![\w-])/,lookbehind:!0}}},url:{pattern:RegExp("\\burl\\((?:"+
r.source+"|(?:[^\\\\\r\n()\"']|\\\\[^])*)\\)","i"),greedy:!0,inside:{function:/^url/i,punctuation:/^\(|\)$/,string:{pattern:RegExp("^"+r.source+"$"),alias:"url"}}},selector:{pattern:RegExp("(^|[{}\\s])[^{}\\s](?:[^{};\"'\\s]|\\s+(?![\\s{])|"+r.source+")*(?=\\s*\\{)"),lookbehind:!0},string:{pattern:r,greedy:!0},property:{pattern:/(^|[^-\w\xA0-\uFFFF])(?!\s)[-_a-z\xA0-\uFFFF](?:(?!\s)[-\w\xA0-\uFFFF])*(?=\s*:)/i,lookbehind:!0},important:/!important\b/i,function:{pattern:/(^|[^-a-z0-9])[-a-z0-9]+(?=\()/i,
lookbehind:!0},punctuation:/[(){};:,]/};h.languages.css.atrule.inside.rest=h.languages.css;(h=h.languages.markup)&&(h.tag.addInlined("style","css"),h.tag.addAttribute("style","css"))}(Prism);
!function(h){var r=/("|')(?:\\(?:\r\n|[\s\S])|(?!\1)[^\\\r\n])*\1/;h.languages.css.selector={pattern:h.languages.css.selector.pattern,lookbehind:!0,inside:r={"pseudo-element":/:(?:after|before|first-letter|first-line|selection)|::[-\w]+/,"pseudo-class":/:[-\w]+/,class:/\.[-\w]+/,id:/#[-\w]+/,attribute:{pattern:RegExp("\\[(?:[^[\\]\"']|"+r.source+")*\\]"),greedy:!0,inside:{punctuation:/^\[|\]$/,"case-sensitivity":{pattern:/(\s)[si]$/i,lookbehind:!0,alias:"keyword"},namespace:{pattern:/^(\s*)(?:(?!\s)[-*\w\xA0-\uFFFF])*\|(?!=)/,
lookbehind:!0,inside:{punctuation:/\|$/}},"attr-name":{pattern:/^(\s*)(?:(?!\s)[-\w\xA0-\uFFFF])+/,lookbehind:!0},"attr-value":[r,{pattern:/(=\s*)(?:(?!\s)[-\w\xA0-\uFFFF])+(?=\s*$)/,lookbehind:!0}],operator:/[|~*^$]?=/}},"n-th":[{pattern:/(\(\s*)[+-]?\d*[\dn](?:\s*[+-]\s*\d+)?(?=\s*\))/,lookbehind:!0,inside:{number:/[\dn]+/,operator:/[+-]/}},{pattern:/(\(\s*)(?:even|odd)(?=\s*\))/i,lookbehind:!0}],combinator:/>|\+|~|\|\|/,punctuation:/[(),]/}};h.languages.css.atrule.inside["selector-function-argument"].inside=
r;h.languages.insertBefore("css","property",{variable:{pattern:/(^|[^-\w\xA0-\uFFFF])--(?!\s)[-_a-z\xA0-\uFFFF](?:(?!\s)[-\w\xA0-\uFFFF])*/i,lookbehind:!0}});r={pattern:/(\b\d+)(?:%|[a-z]+(?![\w-]))/,lookbehind:!0};var l={pattern:/(^|[^\w.-])-?(?:\d+(?:\.\d+)?|\.\d+)/,lookbehind:!0};h.languages.insertBefore("css","function",{operator:{pattern:/(\s)[+\-*\/](?=\s)/,lookbehind:!0},hexcode:{pattern:/\B#[\da-f]{3,8}\b/i,alias:"color"},color:[{pattern:/(^|[^\w-])(?:AliceBlue|AntiqueWhite|Aqua|Aquamarine|Azure|Beige|Bisque|Black|BlanchedAlmond|Blue|BlueViolet|Brown|BurlyWood|CadetBlue|Chartreuse|Chocolate|Coral|CornflowerBlue|Cornsilk|Crimson|Cyan|DarkBlue|DarkCyan|DarkGoldenRod|DarkGr[ae]y|DarkGreen|DarkKhaki|DarkMagenta|DarkOliveGreen|DarkOrange|DarkOrchid|DarkRed|DarkSalmon|DarkSeaGreen|DarkSlateBlue|DarkSlateGr[ae]y|DarkTurquoise|DarkViolet|DeepPink|DeepSkyBlue|DimGr[ae]y|DodgerBlue|FireBrick|FloralWhite|ForestGreen|Fuchsia|Gainsboro|GhostWhite|Gold|GoldenRod|Gr[ae]y|Green|GreenYellow|HoneyDew|HotPink|IndianRed|Indigo|Ivory|Khaki|Lavender|LavenderBlush|LawnGreen|LemonChiffon|LightBlue|LightCoral|LightCyan|LightGoldenRodYellow|LightGr[ae]y|LightGreen|LightPink|LightSalmon|LightSeaGreen|LightSkyBlue|LightSlateGr[ae]y|LightSteelBlue|LightYellow|Lime|LimeGreen|Linen|Magenta|Maroon|MediumAquaMarine|MediumBlue|MediumOrchid|MediumPurple|MediumSeaGreen|MediumSlateBlue|MediumSpringGreen|MediumTurquoise|MediumVioletRed|MidnightBlue|MintCream|MistyRose|Moccasin|NavajoWhite|Navy|OldLace|Olive|OliveDrab|Orange|OrangeRed|Orchid|PaleGoldenRod|PaleGreen|PaleTurquoise|PaleVioletRed|PapayaWhip|PeachPuff|Peru|Pink|Plum|PowderBlue|Purple|RebeccaPurple|Red|RosyBrown|RoyalBlue|SaddleBrown|Salmon|SandyBrown|SeaGreen|SeaShell|Sienna|Silver|SkyBlue|SlateBlue|SlateGr[ae]y|Snow|SpringGreen|SteelBlue|Tan|Teal|Thistle|Tomato|Transparent|Turquoise|Violet|Wheat|White|WhiteSmoke|Yellow|YellowGreen)(?![\w-])/i,
lookbehind:!0},{pattern:/\b(?:hsl|rgb)\(\s*\d{1,3}\s*,\s*\d{1,3}%?\s*,\s*\d{1,3}%?\s*\)\B|\b(?:hsl|rgb)a\(\s*\d{1,3}\s*,\s*\d{1,3}%?\s*,\s*\d{1,3}%?\s*,\s*(?:0|0?\.\d+|1)\s*\)\B/i,inside:{unit:r,number:l,function:/[\w-]+(?=\()/,punctuation:/[(),]/}}],entity:/\\[\da-f]{1,8}/i,unit:r,number:l})}(Prism);
!function(){if("undefined"!=typeof Prism){var h=/\b([a-z]{3,7}:\/\/|tel:)[\w\-+%~/.:=&!$'()*,;@]+(?:\?[\w\-+%~/.:=?&!$'()*,;@]*)?(?:#[\w\-+%~/.:#=?&!$'()*,;@]*)?/,r=/\b\S+@[\w.]+[a-z]{2}/,l=/\[([^\]]+)\]\(([^)]+)\)/,f=["comment","url","attr-value","string"];Prism.plugins.autolinker={processGrammar:function(b){b&&!b["url-link"]&&(Prism.languages.DFS(b,function(a,c,e){f.indexOf(e)>-1&&!Array.isArray(c)&&(c.pattern||(c=this[a]={pattern:c}),c.inside=c.inside||{},"comment"==e&&(c.inside["md-link"]=l),
"attr-value"==e?Prism.languages.insertBefore("inside","punctuation",{"url-link":h},c):c.inside["url-link"]=h,c.inside["email-link"]=r)}),b["url-link"]=h,b["email-link"]=r)}};Prism.hooks.add("before-highlight",function(b){Prism.plugins.autolinker.processGrammar(b.grammar)});Prism.hooks.add("wrap",function(b){if(/-link$/.test(b.type)){b.tag="a";var a=b.content;if("email-link"==b.type&&0!=a.indexOf("mailto:"))a="mailto:"+a;else if("md-link"==b.type){var c=b.content.match(l);a=c[2];b.content=c[1]}b.attributes.href=
a;try{b.content=decodeURIComponent(b.content)}catch(e){}}})}}();
!function(){if("undefined"!=typeof Prism){if(Prism.languages.css&&(Prism.languages.css.selector.pattern?(Prism.languages.css.selector.inside["pseudo-class"]=/:[\w-]+/,Prism.languages.css.selector.inside["pseudo-element"]=/::[\w-]+/):Prism.languages.css.selector={pattern:Prism.languages.css.selector,inside:{"pseudo-class":/:[\w-]+/,"pseudo-element":/::[\w-]+/}}),Prism.languages.markup){Prism.languages.markup.tag.inside.tag.inside["tag-id"]=/[\w-]+/;var h={a:1,abbr:1,acronym:1,b:1,basefont:1,bdo:1,
big:1,blink:1,cite:1,code:1,dfn:1,em:1,kbd:1,i:1,rp:1,rt:1,ruby:1,s:1,samp:1,small:1,spacer:1,strike:1,strong:1,sub:1,sup:1,time:1,tt:1,u:1,var:1,wbr:1,noframes:1,summary:1,command:1,dt:1,dd:1,figure:1,figcaption:1,center:1,section:1,nav:1,article:1,aside:1,hgroup:1,header:1,footer:1,address:1,noscript:1,isIndex:1,main:1,mark:1,marquee:1,meter:1,menu:1};var r={animateColor:1,animateMotion:1,animateTransform:1,glyph:1,feBlend:1,feColorMatrix:1,feComponentTransfer:1,feFuncR:1,feFuncG:1,feFuncB:1,feFuncA:1,
feComposite:1,feConvolveMatrix:1,feDiffuseLighting:1,feDisplacementMap:1,feFlood:1,feGaussianBlur:1,feImage:1,feMerge:1,feMergeNode:1,feMorphology:1,feOffset:1,feSpecularLighting:1,feTile:1,feTurbulence:1,feDistantLight:1,fePointLight:1,feSpotLight:1,linearGradient:1,radialGradient:1,altGlyph:1,textPath:1,tref:1,altglyph:1,textpath:1,altglyphdef:1,altglyphitem:1,clipPath:1,"color-profile":1,cursor:1,"font-face":1,"font-face-format":1,"font-face-name":1,"font-face-src":1,"font-face-uri":1,foreignObject:1,
glyphRef:1,hkern:1,vkern:1};var l={}}var f;Prism.hooks.add("wrap",function(b){if(("tag-id"==b.type||"property"==b.type&&0!=b.content.indexOf("-")||"rule"==b.type&&0!=b.content.indexOf("@-")||"pseudo-class"==b.type&&0!=b.content.indexOf(":-")||"pseudo-element"==b.type&&0!=b.content.indexOf("::-")||"attr-name"==b.type&&0!=b.content.indexOf("data-"))&&-1===b.content.indexOf("<")&&("css"==b.language||"scss"==b.language||"markup"==b.language)){var a="https://webplatform.github.io/docs/",c=b.content;if("css"==
b.language||"scss"==b.language)a+="css/","property"==b.type?a+="properties/":"rule"==b.type?(a+="atrules/",c=c.substring(1)):"pseudo-class"==b.type?(a+="selectors/pseudo-classes/",c=c.substring(1)):"pseudo-element"==b.type&&(a+="selectors/pseudo-elements/",c=c.substring(2));else if("markup"==b.language)if("tag-id"==b.type){if(!(f=function(e){var m=e.toLowerCase();if(h[m])return"html";if(r[e])return"svg";if(l[e])return"mathml";if(0!==h[m]&&"undefined"!=typeof document){var p=(document.createElement(e).toString().match(/\[object HTML(.+)Element\]/)||
[])[1];if(p&&"Unknown"!=p)return h[m]=1,"html"}return(h[m]=0,0!==r[e]&&"undefined"!=typeof document)&&(m=(document.createElementNS("http://www.w3.org/2000/svg",e).toString().match(/\[object SVG(.+)Element\]/)||[])[1])&&"Unknown"!=m?(r[e]=1,"svg"):(r[e]=0,0!==l[e]&&0===e.indexOf("m")?(l[e]=1,"mathml"):(l[e]=0,null))}(b.content)||f))return;a+=f+"/elements/"}else if("attr-name"==b.type){if(!f)return;a+=f+"/attributes/"}b.tag="a";b.attributes.href=a+c;b.attributes.target="_blank"}})}}();
!function(){function h(b,a){return f+(l?l(b,a):b)}if("undefined"!=typeof Prism){var r,l,f="";Prism.plugins.customClass={add:function(b){r=b},map:function(b){l="function"==typeof b?b:function(a){return b[a]||a}},prefix:function(b){f=b||""},apply:h};Prism.hooks.add("wrap",function(b){if(r){var a=r({content:b.content,type:b.type,language:b.language});Array.isArray(a)?b.classes.push.apply(b.classes,a):a&&b.classes.push(a)}(l||f)&&(b.classes=b.classes.map(function(c){return h(c,b.language)}))})}}();
!function(){if("undefined"!=typeof Prism&&"undefined"!=typeof document){Element.prototype.matches||(Element.prototype.matches=Element.prototype.msMatchesSelector||Element.prototype.webkitMatchesSelector);var h={js:"javascript",py:"python",rb:"ruby",ps1:"powershell",psm1:"powershell",sh:"bash",bat:"batch",h:"c",tex:"latex"};Prism.hooks.add("before-highlightall",function(l){l.selector+=', pre[data-src]:not([data-src-status="loaded"]):not([data-src-status="loading"])'});Prism.hooks.add("before-sanity-check",
function(l){var f=l.element;if(f.matches('pre[data-src]:not([data-src-status="loaded"]):not([data-src-status="loading"])')){l.code="";f.setAttribute("data-src-status","loading");var b=f.appendChild(document.createElement("CODE"));b.textContent="Loading\u2026";var a=f.getAttribute("data-src");l=l.language;"none"===l&&(l=(/\.(\w+)$/.exec(a)||[,"none"])[1],l=h[l]||l);Prism.util.setLanguage(b,l);Prism.util.setLanguage(f,l);var c=Prism.plugins.autoloader;c&&c.loadLanguages(l);(function(e,m,p){var d=new XMLHttpRequest;
d.open("GET",e,!0);d.onreadystatechange=function(){if(4==d.readyState)if(d.status<400&&d.responseText){var v=d.responseText;f.setAttribute("data-src-status","loaded");var g=f.getAttribute("data-range");if(g=/^\s*(\d+)\s*(?:(,)\s*(?:(\d+)\s*)?)?$/.exec(g||"")){var n=Number(g[1]);var t=g[3];n=g[2]?t?[n,Number(t)]:[n,void 0]:[n,n]}else n=void 0;n&&(v=v.split(/\r\n?|\n/g),g=n[0],n=null==n[1]?v.length:n[1],g<0&&(g+=v.length),g=Math.max(0,Math.min(g-1,v.length)),n<0&&(n+=v.length),n=Math.max(0,Math.min(n,
v.length)),v=v.slice(g,n).join("\n"),f.hasAttribute("data-start")||f.setAttribute("data-start",String(g+1)));b.textContent=v;Prism.highlightElement(b)}else d.status>=400?p("\u2716 Error "+d.status+" while fetching file: "+d.statusText):p("\u2716 Error: File does not exist or is empty")};d.send(null)})(a,0,function(e){f.setAttribute("data-src-status","failed");b.textContent=e})}});Prism.plugins.fileHighlight={highlight:function(l){for(var f=(l||document).querySelectorAll('pre[data-src]:not([data-src-status="loaded"]):not([data-src-status="loading"])'),
b=0;l=f[b++];)Prism.highlightElement(l)}};var r=!1;Prism.fileHighlight=function(){r||(console.warn("Prism.fileHighlight is deprecated. Use `Prism.plugins.fileHighlight.highlight` instead."),r=!0);Prism.plugins.fileHighlight.highlight.apply(this,arguments)}}}();
!function(){if("undefined"!=typeof Prism&&"undefined"!=typeof document){var h=[],r={},l=function(){};Prism.plugins.toolbar={};var f=Prism.plugins.toolbar.registerButton=function(a,c){var e="function"==typeof c?c:function(m){var p;return"function"==typeof c.onClick?((p=document.createElement("button")).type="button",p.addEventListener("click",function(){c.onClick.call(this,m)})):"string"==typeof c.url?(p=document.createElement("a")).href=c.url:p=document.createElement("span"),c.className&&p.classList.add(c.className),
p.textContent=c.text,p};a in r?console.warn('There is a button with the key "'+a+'" registered already.'):h.push(r[a]=e)},b=Prism.plugins.toolbar.hook=function(a){var c=a.element.parentNode;if(c&&/pre/i.test(c.nodeName)&&!c.parentNode.classList.contains("code-toolbar")){var e=document.createElement("div");e.classList.add("code-toolbar");c.parentNode.insertBefore(e,c);e.appendChild(c);var m=document.createElement("div");m.classList.add("toolbar");c=h;var p=function(d){for(;d;){var v=d.getAttribute("data-toolbar-order");
if(null!=v)return(v=v.trim()).length?v.split(/\s*,\s*/g):[];d=d.parentElement}}(a.element);p&&(c=p.map(function(d){return r[d]||l}));c.forEach(function(d){if(d=d(a)){var v=document.createElement("div");v.classList.add("toolbar-item");v.appendChild(d);m.appendChild(v)}});e.appendChild(m)}};f("label",function(a){if((a=a.element.parentNode)&&/pre/i.test(a.nodeName)&&a.hasAttribute("data-label")){var c,e=a.getAttribute("data-label");try{var m=document.querySelector("template#"+e)}catch(p){}return m?c=
m.content:(a.hasAttribute("data-url")?(c=document.createElement("a")).href=a.getAttribute("data-url"):c=document.createElement("span"),c.textContent=e),c}});Prism.hooks.add("complete",b)}}();
!function(){if("undefined"!=typeof Prism&&"undefined"!=typeof document)if(Prism.plugins.toolbar){var h={none:"Plain text",plain:"Plain text",plaintext:"Plain text",text:"Plain text",txt:"Plain text",html:"HTML",xml:"XML",svg:"SVG",mathml:"MathML",ssml:"SSML",rss:"RSS",css:"CSS",clike:"C-like",js:"JavaScript",abap:"ABAP",abnf:"ABNF",al:"AL",antlr4:"ANTLR4",g4:"ANTLR4",apacheconf:"Apache Configuration",apl:"APL",aql:"AQL",ino:"Arduino",arff:"ARFF",armasm:"ARM Assembly","arm-asm":"ARM Assembly",art:"Arturo",
asciidoc:"AsciiDoc",adoc:"AsciiDoc",aspnet:"ASP.NET (C#)",asm6502:"6502 Assembly",asmatmel:"Atmel AVR Assembly",autohotkey:"AutoHotkey",autoit:"AutoIt",avisynth:"AviSynth",avs:"AviSynth","avro-idl":"Avro IDL",avdl:"Avro IDL",awk:"AWK",gawk:"GAWK",sh:"Shell",basic:"BASIC",bbcode:"BBcode",bbj:"BBj",bnf:"BNF",rbnf:"RBNF",bqn:"BQN",bsl:"BSL (1C:Enterprise)",oscript:"OneScript",csharp:"C#",cs:"C#",dotnet:"C#",cpp:"C++",cfscript:"CFScript",cfc:"CFScript",cil:"CIL",cilkc:"Cilk/C","cilk-c":"Cilk/C",cilkcpp:"Cilk/C++",
"cilk-cpp":"Cilk/C++",cilk:"Cilk/C++",cmake:"CMake",cobol:"COBOL",coffee:"CoffeeScript",conc:"Concurnas",csp:"Content-Security-Policy","css-extras":"CSS Extras",csv:"CSV",cue:"CUE",dataweave:"DataWeave",dax:"DAX",django:"Django/Jinja2",jinja2:"Django/Jinja2","dns-zone-file":"DNS zone file","dns-zone":"DNS zone file",dockerfile:"Docker",dot:"DOT (Graphviz)",gv:"DOT (Graphviz)",ebnf:"EBNF",editorconfig:"EditorConfig",ejs:"EJS",etlua:"Embedded Lua templating",erb:"ERB","excel-formula":"Excel Formula",
xlsx:"Excel Formula",xls:"Excel Formula",fsharp:"F#","firestore-security-rules":"Firestore security rules",ftl:"FreeMarker Template Language",gml:"GameMaker Language",gamemakerlanguage:"GameMaker Language",gap:"GAP (CAS)",gcode:"G-code",gdscript:"GDScript",gedcom:"GEDCOM",gettext:"gettext",po:"gettext",glsl:"GLSL",gn:"GN",gni:"GN","linker-script":"GNU Linker Script",ld:"GNU Linker Script","go-module":"Go module","go-mod":"Go module",graphql:"GraphQL",hbs:"Handlebars",hs:"Haskell",hcl:"HCL",hlsl:"HLSL",
http:"HTTP",hpkp:"HTTP Public-Key-Pins",hsts:"HTTP Strict-Transport-Security",ichigojam:"IchigoJam","icu-message-format":"ICU Message Format",idr:"Idris",ignore:".ignore",gitignore:".gitignore",hgignore:".hgignore",npmignore:".npmignore",inform7:"Inform 7",javadoc:"JavaDoc",javadoclike:"JavaDoc-like",javastacktrace:"Java stack trace",jq:"JQ",jsdoc:"JSDoc","js-extras":"JS Extras",json:"JSON",webmanifest:"Web App Manifest",json5:"JSON5",jsonp:"JSONP",jsstacktrace:"JS stack trace","js-templates":"JS Templates",
keepalived:"Keepalived Configure",kts:"Kotlin Script",kt:"Kotlin",kumir:"KuMir (\u041a\u0443\u041c\u0438\u0440)",kum:"KuMir (\u041a\u0443\u041c\u0438\u0440)",latex:"LaTeX",tex:"TeX",context:"ConTeXt",lilypond:"LilyPond",ly:"LilyPond",emacs:"Lisp",elisp:"Lisp","emacs-lisp":"Lisp",llvm:"LLVM IR",log:"Log file",lolcode:"LOLCODE",magma:"Magma (CAS)",md:"Markdown","markup-templating":"Markup templating",matlab:"MATLAB",maxscript:"MAXScript",mel:"MEL",metafont:"METAFONT",mongodb:"MongoDB",moon:"MoonScript",
n1ql:"N1QL",n4js:"N4JS",n4jsd:"N4JS","nand2tetris-hdl":"Nand To Tetris HDL",naniscript:"Naninovel Script",nani:"Naninovel Script",nasm:"NASM",neon:"NEON",nginx:"nginx",nsis:"NSIS",objectivec:"Objective-C",objc:"Objective-C",ocaml:"OCaml",opencl:"OpenCL",openqasm:"OpenQasm",qasm:"OpenQasm",parigp:"PARI/GP",objectpascal:"Object Pascal",psl:"PATROL Scripting Language",pcaxis:"PC-Axis",px:"PC-Axis",peoplecode:"PeopleCode",pcode:"PeopleCode",php:"PHP",phpdoc:"PHPDoc","php-extras":"PHP Extras","plant-uml":"PlantUML",
plantuml:"PlantUML",plsql:"PL/SQL",powerquery:"PowerQuery",pq:"PowerQuery",mscript:"PowerQuery",powershell:"PowerShell",promql:"PromQL",properties:".properties",protobuf:"Protocol Buffers",purebasic:"PureBasic",pbfasm:"PureBasic",purs:"PureScript",py:"Python",qsharp:"Q#",qs:"Q#",q:"Q (kdb+ database)",qml:"QML",rkt:"Racket",cshtml:"Razor C#",razor:"Razor C#",jsx:"React JSX",tsx:"React TSX",renpy:"Ren'py",rpy:"Ren'py",res:"ReScript",rest:"reST (reStructuredText)",robotframework:"Robot Framework",robot:"Robot Framework",
rb:"Ruby",sas:"SAS",sass:"Sass (Sass)",scss:"Sass (SCSS)","shell-session":"Shell session","sh-session":"Shell session",shellsession:"Shell session",sml:"SML",smlnj:"SML/NJ",solidity:"Solidity (Ethereum)",sol:"Solidity (Ethereum)","solution-file":"Solution file",sln:"Solution file",soy:"Soy (Closure Template)",sparql:"SPARQL",rq:"SPARQL","splunk-spl":"Splunk SPL",sqf:"SQF: Status Quo Function (Arma 3)",sql:"SQL",stata:"Stata Ado",iecst:"Structured Text (IEC 61131-3)",supercollider:"SuperCollider",
sclang:"SuperCollider",systemd:"Systemd configuration file","t4-templating":"T4 templating","t4-cs":"T4 Text Templates (C#)",t4:"T4 Text Templates (C#)","t4-vb":"T4 Text Templates (VB)",tap:"TAP",tt2:"Template Toolkit 2",toml:"TOML",trickle:"trickle",troy:"troy",trig:"TriG",ts:"TypeScript",tsconfig:"TSConfig",uscript:"UnrealScript",uc:"UnrealScript",uorazor:"UO Razor Script",uri:"URI",url:"URL",vbnet:"VB.Net",vhdl:"VHDL",vim:"vim","visual-basic":"Visual Basic",vba:"VBA",vb:"Visual Basic",wasm:"WebAssembly",
"web-idl":"Web IDL",webidl:"Web IDL",wgsl:"WGSL",wiki:"Wiki markup",wolfram:"Wolfram language",nb:"Mathematica Notebook",wl:"Wolfram language",xeoracube:"XeoraCube","xml-doc":"XML doc (.net)",xojo:"Xojo (REALbasic)",xquery:"XQuery",yaml:"YAML",yml:"YAML",yang:"YANG"};Prism.plugins.toolbar.registerButton("show-language",function(r){var l=r.element.parentNode;if(l&&/pre/i.test(l.nodeName)){var f;if(r=l.getAttribute("data-language")||h[r.language]||((f=r.language)?(f.substring(0,1).toUpperCase()+f.substring(1)).replace(/s(?=cript)/,
"S"):f))return f=document.createElement("span"),f.textContent=r,f}})}else console.warn("Show Languages plugin loaded before Toolbar plugin.")}();"undefined"!=typeof Prism&&Prism.hooks.add("wrap",function(h){"keyword"===h.type&&h.classes.push("keyword-"+h.content)});
!function(){if("undefined"!=typeof Prism&&"undefined"!=typeof document){var h=/<\/?(?!\d)[^\s>\/=$<%]+(?:\s(?:\s*[^\s>\/=]+(?:\s*=\s*(?:"[^"]*"|'[^']*'|[^\s'">=]+(?=[\s>]))|(?=[\s/>])))+)?\s*\/?>/g,r=/^#?((?:[\da-f]){3,4}|(?:[\da-f]{2}){3,4})$/i,l=[function(f){if(f=r.exec(f)){for(var b=(f=f[1]).length>=6?2:1,a=f.length/b,c=1==b?1/15:1/255,e=[],m=0;m<a;m++){var p=parseInt(f.substr(m*b,b),16);e.push(p*c)}return 3==a&&e.push(1),"rgba("+e.slice(0,3).map(function(d){return String(Math.round(255*d))}).join(",")+
","+String(Number(e[3].toFixed(3)))+")"}},function(f){var b=(new Option).style;return b.color=f,b.color?f:void 0}];Prism.hooks.add("wrap",function(f){if("color"===f.type||f.classes.indexOf("color")>=0){for(var b,a=f.content,c=a.split(h).join(""),e=0,m=l.length;e<m&&!b;e++)b=l[e](c);b&&(f.content='<span class="inline-color-wrapper"><span class="inline-color" style="background-color:'+b+';"></span></span>'+a)}})}}();
!function(){if("undefined"!=typeof Prism&&"undefined"!=typeof document&&Function.prototype.bind){var h,r,l={gradient:{create:(h={},r=function(a){if(h[a])return h[a];var c=a.match(/^(\b|\B-[a-z]{1,10}-)((?:repeating-)?(?:linear|radial)-gradient)/),e=c&&c[1];c=c&&c[2];var m=a.replace(/^(?:\b|\B-[a-z]{1,10}-)(?:repeating-)?(?:linear|radial)-gradient\(|\)$/g,"").split(/\s*,\s*/);return c.indexOf("linear")>=0?h[a]=function(p,d,v){var g="180deg";return/^(?:-?(?:\d+(?:\.\d+)?|\.\d+)(?:deg|rad)|to\b|top|right|bottom|left)/.test(v[0])&&
(g=v.shift()).indexOf("to ")<0&&(g.indexOf("top")>=0?g=g.indexOf("left")>=0?"to bottom right":g.indexOf("right")>=0?"to bottom left":"to bottom":g.indexOf("bottom")>=0?g=g.indexOf("left")>=0?"to top right":g.indexOf("right")>=0?"to top left":"to top":g.indexOf("left")>=0?g="to right":g.indexOf("right")>=0?g="to left":p&&(g.indexOf("deg")>=0?g=90-parseFloat(g)+"deg":g.indexOf("rad")>=0&&(g=Math.PI/2-parseFloat(g)+"rad"))),d+"("+g+","+v.join(",")+")"}(e,c,m):c.indexOf("radial")>=0?h[a]=function(p,d,
v){if(v[0].indexOf("at")<0){p="center";var g="ellipse",n="farthest-corner";if(/\b(?:bottom|center|left|right|top)\b|^\d+/.test(v[0])&&(p=v.shift().replace(/\s*-?\d+(?:deg|rad)\s*/,"")),/\b(?:circle|closest|contain|cover|ellipse|farthest)\b/.test(v[0])){var t=v.shift().split(/\s+/);!t[0]||"circle"!==t[0]&&"ellipse"!==t[0]||(g=t.shift());t[0]&&(n=t.shift());"cover"===n?n="farthest-corner":"contain"===n&&(n="clothest-side")}return d+"("+g+" "+n+" at "+p+","+v.join(",")+")"}return d+"("+v.join(",")+")"}(0,
c,m):h[a]=c+"("+m.join(",")+")"},function(){new Prism.plugins.Previewer("gradient",function(a){return this.firstChild.style.backgroundImage="",this.firstChild.style.backgroundImage=r(a),!!this.firstChild.style.backgroundImage},"*",function(){this._elt.innerHTML="<div></div>"})}),tokens:{gradient:{pattern:/(?:\b|\B-[a-z]{1,10}-)(?:repeating-)?(?:linear|radial)-gradient\((?:(?:hsl|rgb)a?\(.+?\)|[^\)])+\)/gi,inside:{function:/[\w-]+(?=\()/,punctuation:/[(),]/}}},languages:{css:!0,less:!0,sass:[{lang:"sass",
before:"punctuation",inside:"inside",root:Prism.languages.sass&&Prism.languages.sass["variable-line"]},{lang:"sass",before:"punctuation",inside:"inside",root:Prism.languages.sass&&Prism.languages.sass["property-line"]}],scss:!0,stylus:[{lang:"stylus",before:"func",inside:"rest",root:Prism.languages.stylus&&Prism.languages.stylus["property-declaration"].inside},{lang:"stylus",before:"func",inside:"rest",root:Prism.languages.stylus&&Prism.languages.stylus["variable-declaration"].inside}]}},angle:{create:function(){new Prism.plugins.Previewer("angle",
function(a){var c,e=parseFloat(a);a=a.match(/[a-z]+$/i);if(!e||!a)return!1;switch(a[0]){case "deg":var m=360;break;case "grad":m=400;break;case "rad":m=2*Math.PI;break;case "turn":m=1}return c=100*e/m,c%=100,this[(e<0?"set":"remove")+"Attribute"]("data-negative",""),this.querySelector("circle").style.strokeDasharray=Math.abs(c)+",500",!0},"*",function(){this._elt.innerHTML='<svg viewBox="0 0 64 64"><circle r="16" cy="32" cx="32"></circle></svg>'})},tokens:{angle:/(?:\b|\B-|(?=\B\.))(?:\d+(?:\.\d+)?|\.\d+)(?:deg|g?rad|turn)\b/i},
languages:{css:!0,less:!0,markup:{lang:"markup",before:"punctuation",inside:"inside",root:Prism.languages.markup&&Prism.languages.markup.tag.inside["attr-value"]},sass:[{lang:"sass",inside:"inside",root:Prism.languages.sass&&Prism.languages.sass["property-line"]},{lang:"sass",before:"operator",inside:"inside",root:Prism.languages.sass&&Prism.languages.sass["variable-line"]}],scss:!0,stylus:[{lang:"stylus",before:"func",inside:"rest",root:Prism.languages.stylus&&Prism.languages.stylus["property-declaration"].inside},
{lang:"stylus",before:"func",inside:"rest",root:Prism.languages.stylus&&Prism.languages.stylus["variable-declaration"].inside}]}},color:{create:function(){new Prism.plugins.Previewer("color",function(a){return this.style.backgroundColor="",this.style.backgroundColor=a,!!this.style.backgroundColor})},tokens:{color:[Prism.languages.css.hexcode].concat(Prism.languages.css.color)},languages:{css:!1,less:!0,markup:{lang:"markup",before:"punctuation",inside:"inside",root:Prism.languages.markup&&Prism.languages.markup.tag.inside["attr-value"]},
sass:[{lang:"sass",before:"punctuation",inside:"inside",root:Prism.languages.sass&&Prism.languages.sass["variable-line"]},{lang:"sass",inside:"inside",root:Prism.languages.sass&&Prism.languages.sass["property-line"]}],scss:!1,stylus:[{lang:"stylus",before:"hexcode",inside:"rest",root:Prism.languages.stylus&&Prism.languages.stylus["property-declaration"].inside},{lang:"stylus",before:"hexcode",inside:"rest",root:Prism.languages.stylus&&Prism.languages.stylus["variable-declaration"].inside}]}},easing:{create:function(){new Prism.plugins.Previewer("easing",
function(a){var c=(a={linear:"0,0,1,1",ease:".25,.1,.25,1","ease-in":".42,0,1,1","ease-out":"0,0,.58,1","ease-in-out":".42,0,.58,1"}[a]||a).match(/-?(?:\d+(?:\.\d+)?|\.\d+)/g);return 4===c.length?(c=c.map(function(e,m){return 100*(m%2?1-e:e)}),this.querySelector("path").setAttribute("d","M0,100 C"+c[0]+","+c[1]+", "+c[2]+","+c[3]+", 100,0"),a=this.querySelectorAll("line"),a[0].setAttribute("x2",c[0]),a[0].setAttribute("y2",c[1]),a[1].setAttribute("x2",c[2]),a[1].setAttribute("y2",c[3]),!0):!1},"*",
function(){this._elt.innerHTML='<svg viewBox="-20 -20 140 140" width="100" height="100"><defs><marker id="prism-previewer-easing-marker" viewBox="0 0 4 4" refX="2" refY="2" markerUnits="strokeWidth"><circle cx="2" cy="2" r="1.5" /></marker></defs><path d="M0,100 C20,50, 40,30, 100,0" /><line x1="0" y1="100" x2="20" y2="50" marker-start="url(#prism-previewer-easing-marker)" marker-end="url(#prism-previewer-easing-marker)" /><line x1="100" y1="0" x2="40" y2="30" marker-start="url(#prism-previewer-easing-marker)" marker-end="url(#prism-previewer-easing-marker)" /></svg>'})},
tokens:{easing:{pattern:/\bcubic-bezier\((?:-?(?:\d+(?:\.\d+)?|\.\d+),\s*){3}-?(?:\d+(?:\.\d+)?|\.\d+)\)\B|\b(?:ease(?:-in)?(?:-out)?|linear)(?=\s|[;}]|$)/i,inside:{function:/[\w-]+(?=\()/,punctuation:/[(),]/}}},languages:{css:!0,less:!0,sass:[{lang:"sass",inside:"inside",before:"punctuation",root:Prism.languages.sass&&Prism.languages.sass["variable-line"]},{lang:"sass",inside:"inside",root:Prism.languages.sass&&Prism.languages.sass["property-line"]}],scss:!0,stylus:[{lang:"stylus",before:"hexcode",
inside:"rest",root:Prism.languages.stylus&&Prism.languages.stylus["property-declaration"].inside},{lang:"stylus",before:"hexcode",inside:"rest",root:Prism.languages.stylus&&Prism.languages.stylus["variable-declaration"].inside}]}},time:{create:function(){new Prism.plugins.Previewer("time",function(a){var c=parseFloat(a);a=a.match(/[a-z]+$/i);return!(!c||!a||(a=a[0],this.querySelector("circle").style.animationDuration=2*c+a,0))},"*",function(){this._elt.innerHTML='<svg viewBox="0 0 64 64"><circle r="16" cy="32" cx="32"></circle></svg>'})},
tokens:{time:/(?:\b|\B-|(?=\B\.))(?:\d+(?:\.\d+)?|\.\d+)m?s\b/i},languages:{css:!0,less:!0,markup:{lang:"markup",before:"punctuation",inside:"inside",root:Prism.languages.markup&&Prism.languages.markup.tag.inside["attr-value"]},sass:[{lang:"sass",inside:"inside",root:Prism.languages.sass&&Prism.languages.sass["property-line"]},{lang:"sass",before:"operator",inside:"inside",root:Prism.languages.sass&&Prism.languages.sass["variable-line"]}],scss:!0,stylus:[{lang:"stylus",before:"hexcode",inside:"rest",
root:Prism.languages.stylus&&Prism.languages.stylus["property-declaration"].inside},{lang:"stylus",before:"hexcode",inside:"rest",root:Prism.languages.stylus&&Prism.languages.stylus["variable-declaration"].inside}]}}},f=function(a,c,e,m){this._elt=null;this._type=a;this._token=null;this.updater=c;this._mouseout=this.mouseout.bind(this);this.initializer=m;var p=this;e||=["*"];Array.isArray(e)||(e=[e]);e.forEach(function(d){"string"!=typeof d&&(d=d.lang);f.byLanguages[d]||(f.byLanguages[d]=[]);f.byLanguages[d].indexOf(p)<
0&&f.byLanguages[d].push(p)});f.byType[a]=this},b;for(b in f.prototype.init=function(){this._elt||(this._elt=document.createElement("div"),this._elt.className="prism-previewer prism-previewer-"+this._type,document.body.appendChild(this._elt),this.initializer&&this.initializer())},f.prototype.isDisabled=function(a){do if(a.hasAttribute&&a.hasAttribute("data-previewers"))return-1===(a.getAttribute("data-previewers")||"").split(/\s+/).indexOf(this._type);while(a=a.parentNode);return!1},f.prototype.check=
function(a){if(!a.classList.contains("token")||!this.isDisabled(a)){do if(a.classList&&a.classList.contains("token")&&a.classList.contains(this._type))break;while(a=a.parentNode);a&&a!==this._token&&(this._token=a,this.show())}},f.prototype.mouseout=function(){this._token.removeEventListener("mouseout",this._mouseout,!1);this._token=null;this.hide()},f.prototype.show=function(){var a,c,e,m;if(this._elt||this.init(),this._token)if(this.updater.call(this._elt,this._token.textContent)){this._token.addEventListener("mouseout",
this._mouseout,!1);var p=(c=(a=this._token.getBoundingClientRect()).left,e=a.top,c-=(m=document.documentElement.getBoundingClientRect()).left,{top:e-=m.top,right:innerWidth-c-a.width,bottom:innerHeight-e-a.height,left:c,width:a.width,height:a.height});this._elt.classList.add("active");p.top-this._elt.offsetHeight>0?(this._elt.classList.remove("flipped"),this._elt.style.top=p.top+"px",this._elt.style.bottom=""):(this._elt.classList.add("flipped"),this._elt.style.bottom=p.bottom+"px",this._elt.style.top=
"");this._elt.style.left=p.left+Math.min(200,p.width/2)+"px"}else this.hide()},f.prototype.hide=function(){this._elt.classList.remove("active")},f.byLanguages={},f.byType={},f.initEvents=function(a,c){var e=[];f.byLanguages[c]&&(e=e.concat(f.byLanguages[c]));f.byLanguages["*"]&&(e=e.concat(f.byLanguages["*"]));a.addEventListener("mouseover",function(m){var p=m.target;e.forEach(function(d){d.check(p)})},!1)},Prism.plugins.Previewer=f,Prism.hooks.add("before-highlight",function(a){for(var c in l){var e=
l[c].languages;if(a.language&&e[a.language]&&!e[a.language].initialized){var m=e[a.language];Array.isArray(m)||(m=[m]);m.forEach(function(p){var d,v,g,n;!0===p?(d="important",v=a.language,p=a.language):(d=p.before||"important",v=p.inside||p.lang,g=p.root||Prism.languages,n=p.skip,p=a.language);!n&&Prism.languages[p]&&(Prism.languages.insertBefore(v,d,l[c].tokens,g),a.grammar=Prism.languages[p],e[a.language]={initialized:!0})})}}}),Prism.hooks.add("after-highlight",function(a){(f.byLanguages["*"]||
f.byLanguages[a.language])&&f.initEvents(a.element,a.language)}),l)l[b].create()}}();
!function(){function h(g){return g.indexOf("!")>=0?!1:(g=b[g]||g)in Prism.languages?!0:(g=a[g])&&!g.error&&!1===g.loading}function r(g,n,t){function k(){w||++u===q&&n&&n(g)}"string"==typeof g&&(g=[g]);var q=g.length,u=0,w=!1;0!==q?g.forEach(function(A){!function(x,y,z){function D(){var B=a[x];B||=a[x]={callbacks:[]};B.callbacks.push({success:y,error:z});!G&&h(x)?l(x,"success"):!G&&B.error?l(x,"error"):!G&&B.loading||(B.loading=!0,B.error=!1,function(E,C,H){var F=document.createElement("script");F.src=
E;F.async=!0;F.onload=function(){document.body.removeChild(F);C&&C()};F.onerror=function(){document.body.removeChild(F);H&&H()};document.body.appendChild(F)}(v.languages_path+"prism-"+x+(v.use_minified?".min":"")+".js",function(){B.loading=!1;l(x,"success")},function(){B.loading=!1;B.error=!0;l(x,"error")}))}var G=x.indexOf("!")>=0;x=x.replace("!","");var J=f[x=b[x]||x];J&&J.length?r(J,D,z):D()}(A,k,function(){w||(w=!0,t&&t(A))})}):n&&setTimeout(n,0)}function l(g,n){if(a[g]){g=a[g].callbacks;for(var t=
0,k=g.length;t<k;t++){var q=g[t][n];q&&setTimeout(q,0)}g.length=0}}if("undefined"!=typeof Prism&&"undefined"!=typeof document){var f={javascript:"clike",actionscript:"javascript",apex:["clike","sql"],arduino:"cpp",aspnet:["markup","csharp"],birb:"clike",bison:"c",c:"clike",csharp:"clike",cpp:"c",cfscript:"clike",chaiscript:["clike","cpp"],cilkc:"c",cilkcpp:"cpp",coffeescript:"javascript",crystal:"ruby","css-extras":"css",d:"clike",dart:"clike",django:"markup-templating",ejs:["javascript","markup-templating"],
etlua:["lua","markup-templating"],erb:["ruby","markup-templating"],fsharp:"clike","firestore-security-rules":"clike",flow:"javascript",ftl:"markup-templating",gml:"clike",glsl:"c",go:"clike",gradle:"clike",groovy:"clike",haml:"ruby",handlebars:"markup-templating",haxe:"clike",hlsl:"c",idris:"haskell",java:"clike",javadoc:["markup","java","javadoclike"],jolie:"clike",jsdoc:["javascript","javadoclike","typescript"],"js-extras":"javascript",json5:"json",jsonp:"json","js-templates":"javascript",kotlin:"clike",
latte:["clike","markup-templating","php"],less:"css",lilypond:"scheme",liquid:"markup-templating",markdown:"markup","markup-templating":"markup",mongodb:"javascript",n4js:"javascript",objectivec:"c",opencl:"c",parser:"markup",php:"markup-templating",phpdoc:["php","javadoclike"],"php-extras":"php",plsql:"sql",processing:"clike",protobuf:"clike",pug:["markup","javascript"],purebasic:"clike",purescript:"haskell",qsharp:"clike",qml:"javascript",qore:"clike",racket:"scheme",cshtml:["markup","csharp"],
jsx:["markup","javascript"],tsx:["jsx","typescript"],reason:"clike",ruby:"clike",sass:"css",scss:"css",scala:"java","shell-session":"bash",smarty:"markup-templating",solidity:"clike",soy:"markup-templating",sparql:"turtle",sqf:"clike",squirrel:"clike",stata:["mata","java","python"],"t4-cs":["t4-templating","csharp"],"t4-vb":["t4-templating","vbnet"],tap:"yaml",tt2:["clike","markup-templating"],textile:"markup",twig:"markup-templating",typescript:"javascript",v:"clike",vala:"clike",vbnet:"basic",velocity:"markup",
wiki:"markup",xeora:"markup","xml-doc":"markup",xquery:"markup"},b={html:"markup",xml:"markup",svg:"markup",mathml:"markup",ssml:"markup",atom:"markup",rss:"markup",js:"javascript",g4:"antlr4",ino:"arduino","arm-asm":"armasm",art:"arturo",adoc:"asciidoc",avs:"avisynth",avdl:"avro-idl",gawk:"awk",sh:"bash",shell:"bash",shortcode:"bbcode",rbnf:"bnf",oscript:"bsl",cs:"csharp",dotnet:"csharp",cfc:"cfscript","cilk-c":"cilkc","cilk-cpp":"cilkcpp",cilk:"cilkcpp",coffee:"coffeescript",conc:"concurnas",jinja2:"django",
"dns-zone":"dns-zone-file",dockerfile:"docker",gv:"dot",eta:"ejs",xlsx:"excel-formula",xls:"excel-formula",gamemakerlanguage:"gml",po:"gettext",gni:"gn",ld:"linker-script","go-mod":"go-module",hbs:"handlebars",mustache:"handlebars",hs:"haskell",idr:"idris",gitignore:"ignore",hgignore:"ignore",npmignore:"ignore",webmanifest:"json",kt:"kotlin",kts:"kotlin",kum:"kumir",tex:"latex",context:"latex",ly:"lilypond",emacs:"lisp",elisp:"lisp","emacs-lisp":"lisp",md:"markdown",moon:"moonscript",n4jsd:"n4js",
nani:"naniscript",objc:"objectivec",qasm:"openqasm",objectpascal:"pascal",px:"pcaxis",pcode:"peoplecode",plantuml:"plant-uml",pq:"powerquery",mscript:"powerquery",pbfasm:"purebasic",purs:"purescript",py:"python",qs:"qsharp",rkt:"racket",razor:"cshtml",rpy:"renpy",res:"rescript",robot:"robotframework",rb:"ruby","sh-session":"shell-session",shellsession:"shell-session",smlnj:"sml",sol:"solidity",sln:"solution-file",rq:"sparql",sclang:"supercollider",t4:"t4-cs",trickle:"tremor",troy:"tremor",trig:"turtle",
ts:"typescript",tsconfig:"typoscript",uscript:"unrealscript",uc:"unrealscript",url:"uri",vb:"visual-basic",vba:"visual-basic",webidl:"web-idl",mathematica:"wolfram",nb:"wolfram",wl:"wolfram",xeoracube:"xeora",yml:"yaml"},a={},c="components/",e=Prism.util.currentScript();if(e){var m=/\bplugins\/autoloader\/prism-autoloader\.(?:min\.)?js(?:\?[^\r\n/]*)?$/i,p=/(^|\/)[\w-]+\.(?:min\.)?js(?:\?[^\r\n/]*)?$/i,d=e.getAttribute("data-autoloader-path");null!=d?c=d.trim().replace(/\/?$/,"/"):(e=e.src,m.test(e)?
c=e.replace(m,"components/"):p.test(e)&&(c=e.replace(p,"$1components/")))}var v=Prism.plugins.autoloader={languages_path:c,use_minified:!0,loadLanguages:r};Prism.hooks.add("complete",function(g){var n=g.element;g=g.language;if(n&&g&&"none"!==g){var t=function(k){var q=(k.getAttribute("data-dependencies")||"").trim();q||(k=k.parentElement)&&"pre"===k.tagName.toLowerCase()&&(q=(k.getAttribute("data-dependencies")||"").trim());return q?q.split(/\s*,\s*/g):[]}(n);/^diff-./i.test(g)?(t.push("diff"),t.push(g.substr(5))):
t.push(g);t.every(h)||r(t,function(){Prism.highlightElement(n)})}})}}();
"undefined"!=typeof Prism&&"undefined"!=typeof document&&document.createRange&&(Prism.plugins.KeepMarkup=!0,Prism.hooks.add("before-highlight",function(h){function r(a){for(var c=0,e=a.childNodes.length;c<e;c++){var m=a.childNodes[c];if(1===m.nodeType)if(l&&"span"===m.nodeName.toLowerCase()&&m.classList.contains("token"))r(m);else{var p={element:m,posOpen:f};b.push(p);r(m);p.posClose=f}else 3===m.nodeType&&(f+=m.data.length)}}if(h.element.children.length&&Prism.util.isActive(h.element,"keep-markup",
!0)){var l=Prism.util.isActive(h.element,"drop-tokens",!1),f=0,b=[];r(h.element);b.length&&(h.keepMarkup=b)}}),Prism.hooks.add("after-highlight",function(h){if(h.keepMarkup&&h.keepMarkup.length){var r=function(l,f){for(var b=0,a=l.childNodes.length;b<a;b++){var c=l.childNodes[b];if(1===c.nodeType){if(!r(c,f))return!1}else 3===c.nodeType&&(!f.nodeStart&&f.pos+c.data.length>f.node.posOpen&&(f.nodeStart=c,f.nodeStartPos=f.node.posOpen-f.pos),f.nodeStart&&f.pos+c.data.length>=f.node.posClose&&(f.nodeEnd=
c,f.nodeEndPos=f.node.posClose-f.pos),f.pos+=c.data.length);if(f.nodeStart&&f.nodeEnd)return l=document.createRange(),l.setStart(f.nodeStart,f.nodeStartPos),l.setEnd(f.nodeEnd,f.nodeEndPos),f.node.element.innerHTML="",f.node.element.appendChild(l.extractContents()),l.insertNode(f.node.element),l.detach(),!1}return!0};h.keepMarkup.forEach(function(l){r(h.element,{node:l,pos:0})});h.highlightedCode=h.element.innerHTML}}));
!function(){function h(b){b=b.vars=b.vars||{};return b["command-line"]=b["command-line"]||{}}if("undefined"!=typeof Prism&&"undefined"!=typeof document){var r=/(?:^|\s)command-line(?:\s|$)/,l="".startsWith?function(b,a){return b.startsWith(a)}:function(b,a){return 0===b.indexOf(a)},f="".endsWith?function(b,a){return b.endsWith(a)}:function(b,a){var c=b.length;return b.substring(c-a.length,c)===a};Prism.hooks.add("before-highlight",function(b){var a=h(b);if(!a.complete&&b.code){var c=b.element.parentElement;
if(c&&/pre/i.test(c.nodeName)&&(r.test(c.className)||r.test(b.element.className))){var e=b.element.querySelector(".command-line-prompt");e&&e.remove();var m=b.code.split("\n");a.numberOfLines=m.length;var p=a.outputLines=[],d=c.getAttribute("data-output");e=c.getAttribute("data-filter-output");if(null!==d)d.split(",").forEach(function(g){var n=g.split("-");g=parseInt(n[0],10);n=2===n.length?parseInt(n[1],10):g;if(!isNaN(g)&&!isNaN(n))for(g<1&&(g=1),n>m.length&&(n=m.length),n--,g=--g;g<=n;g++)p[g]=
m[g],m[g]=""});else if(e)for(d=0;d<m.length;d++)l(m[d],e)&&(p[d]=m[d].slice(e.length),m[d]="");a=a.continuationLineIndicies=new Set;e=c.getAttribute("data-continuation-str");c=c.getAttribute("data-filter-continuation");for(d=0;d<m.length;d++){var v=m[d];v&&(e&&f(v,e)&&a.add(d+1),d>0&&c&&l(v,c)&&(m[d]=v.slice(c.length),a.add(d)))}b.code=m.join("\n")}else a.complete=!0}else a.complete=!0});Prism.hooks.add("before-insert",function(b){var a=h(b);if(!a.complete){var c=b.highlightedCode.split("\n");a=a.outputLines||
[];for(var e=0,m=c.length;e<m;e++)a.hasOwnProperty(e)?c[e]='<span class="token output">'+Prism.util.encode(a[e])+"</span>":c[e]='<span class="token command">'+c[e]+"</span>";b.highlightedCode=c.join("\n")}});Prism.hooks.add("complete",function(b){function a(t,k){return(e.getAttribute(t)||k).replace(/"/g,"&quot")}if("command-line"in(b.vars=b.vars||{})){var c=h(b);if(!c.complete){var e=b.element.parentElement;r.test(b.element.className)&&(b.element.className=b.element.className.replace(r," "));r.test(e.className)||
(e.className+=" command-line");var m="",p=c.numberOfLines||0;var d=a("data-prompt","");d=""!==d?'<span data-prompt="'+d+'"></span>':'<span data-user="'+a("data-user","user")+'" data-host="'+a("data-host","localhost")+'"></span>';for(var v=c.continuationLineIndicies||new Set,g='<span data-continuation-prompt="'+a("data-continuation-prompt",">")+'"></span>',n=0;n<p;n++)v.has(n)?m+=g:m+=d;p=document.createElement("span");p.className="command-line-prompt";p.innerHTML=m;m=c.outputLines||[];d=0;for(v=m.length;d<
v;d++)m.hasOwnProperty(d)&&(g=p.children[d],g.removeAttribute("data-user"),g.removeAttribute("data-host"),g.removeAttribute("data-prompt"));b.element.insertBefore(p,b.element.firstChild);c.complete=!0}}})}}();
!function(){function h(b){this.defaults=l({},b)}function r(b){for(var a=0,c=0;c<b.length;++c)b.charCodeAt(c)==9&&(a+=3);return b.length+a}if("undefined"!=typeof Prism){var l=Object.assign||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b},f={"remove-trailing":"boolean","remove-indent":"boolean","left-trim":"boolean","right-trim":"boolean","break-lines":"number",indent:"number","remove-initial-line-feed":"boolean","tabs-to-spaces":"number","spaces-to-tabs":"number"};h.prototype=
{setDefaults:function(b){this.defaults=l(this.defaults,b)},normalize:function(b,a){for(var c in a=l(this.defaults,a)){var e=c.replace(/-(\w)/g,function(m,p){return p.toUpperCase()});"normalize"!==c&&"setDefaults"!==e&&a[c]&&this[e]&&(b=this[e].call(this,b,a[c]))}return b},leftTrim:function(b){return b.replace(/^\s+/,"")},rightTrim:function(b){return b.replace(/\s+$/,"")},tabsToSpaces:function(b,a){return a=0|a||4,b.replace(/\t/g,Array(++a).join(" "))},spacesToTabs:function(b,a){return a=0|a||4,b.replace(RegExp(" {"+
a+"}","g"),"\t")},removeTrailing:function(b){return b.replace(/\s*?$/gm,"")},removeInitialLineFeed:function(b){return b.replace(/^(?:\r?\n|\r)/,"")},removeIndent:function(b){var a=b.match(/^[^\S\n\r]*(?=\S)/gm);return a&&a[0].length?(a.sort(function(c,e){return c.length-e.length}),a[0].length?b.replace(RegExp("^"+a[0],"gm"),""):b):b},indent:function(b,a){return b.replace(/^[^\S\n\r]*(?=\S)/gm,Array(++a).join("\t")+"$&")},breakLines:function(b,a){a=!0===a?80:0|a||80;b=b.split("\n");for(var c=0;c<b.length;++c)if(!(r(b[c])<=
a)){for(var e=b[c].split(/(\s+)/g),m=0,p=0;p<e.length;++p){var d=r(e[p]);(m+=d)>a&&(e[p]="\n"+e[p],m=d)}b[c]=e.join("")}return b.join("\n")}};"undefined"!=typeof module&&module.exports&&(module.exports=h);Prism.plugins.NormalizeWhitespace=new h({"remove-trailing":!0,"remove-indent":!0,"left-trim":!0,"right-trim":!0});Prism.hooks.add("before-sanity-check",function(b){var a=Prism.plugins.NormalizeWhitespace;if((!b.settings||!1!==b.settings["whitespace-normalization"])&&Prism.util.isActive(b.element,
"whitespace-normalization",!0))if(b.element&&b.element.parentNode||!b.code){var c=b.element.parentNode;if(b.code&&c&&"pre"===c.nodeName.toLowerCase()){for(var e in null==b.settings&&(b.settings={}),f)if(Object.hasOwnProperty.call(f,e)){var m=f[e];if(c.hasAttribute("data-"+e))try{var p=JSON.parse(c.getAttribute("data-"+e)||"true");typeof p===m&&(b.settings[e]=p)}catch(n){}}e=c.childNodes;p=m="";for(var d=!1,v=0;v<e.length;++v){var g=e[v];g==b.element?d=!0:"#text"===g.nodeName&&(d?p+=g.nodeValue:m+=
g.nodeValue,c.removeChild(g),--v)}b.element.children.length&&Prism.plugins.KeepMarkup?(b.element.innerHTML=a.normalize(m+b.element.innerHTML+p,b.settings),b.code=b.element.textContent):(b.code=m+b.code+p,b.code=a.normalize(b.code,b.settings))}}else b.code=a.normalize(b.code,b.settings)})}}();
!function(){if("undefined"!=typeof Prism){var h={pattern:/(.)\bdata:[^\/]+\/[^,]+,(?:(?!\1)[\s\S]|\\\1)+(?=\1)/,lookbehind:!0,inside:{"language-css":{pattern:/(data:[^\/]+\/(?:[^+,]+\+)?css,)[\s\S]+/,lookbehind:!0},"language-javascript":{pattern:/(data:[^\/]+\/(?:[^+,]+\+)?javascript,)[\s\S]+/,lookbehind:!0},"language-json":{pattern:/(data:[^\/]+\/(?:[^+,]+\+)?json,)[\s\S]+/,lookbehind:!0},"language-markup":{pattern:/(data:[^\/]+\/(?:[^+,]+\+)?(?:html|xml),)[\s\S]+/,lookbehind:!0}}},r=["url","attr-value",
"string"];Prism.plugins.dataURIHighlight={processGrammar:function(l){l&&!l["data-uri"]&&(Prism.languages.DFS(l,function(f,b,a){r.indexOf(a)>-1&&!Array.isArray(b)&&(b.pattern||(b=this[f]={pattern:b}),b.inside=b.inside||{},"attr-value"==a?Prism.languages.insertBefore("inside",b.inside["url-link"]?"url-link":"punctuation",{"data-uri":h},b):b.inside["url-link"]?Prism.languages.insertBefore("inside","url-link",{"data-uri":h},b):b.inside["data-uri"]=h)}),l["data-uri"]=h)}};Prism.hooks.add("before-highlight",
function(l){if(h.pattern.test(l.code))for(var f in h.inside)if(h.inside.hasOwnProperty(f)&&!h.inside[f].inside&&h.inside[f].pattern.test(l.code)){var b=f.match(/^language-(.+)/)[1];Prism.languages[b]&&(h.inside[f].inside={rest:(a=Prism.languages[b],Prism.plugins.autolinker&&Prism.plugins.autolinker.processGrammar(a),a)})}var a;Prism.plugins.dataURIHighlight.processGrammar(l.grammar)})}}();
!function(){function h(d){var v=Prism.plugins.customClass;return v?v.apply(d,"none"):d}function r(d){d=p.exec(d.id);return document.querySelector("#"+d[1]+("open"==d[2]?"close":"open"))}function l(){Prism.util.isActive(this,"brace-hover",!0)&&[this,r(this)].forEach(function(d){d.classList.add(h("brace-hover"))})}function f(){[this,r(this)].forEach(function(d){d.classList.remove(h("brace-hover"))})}function b(){Prism.util.isActive(this,"brace-select",!0)&&[this,r(this)].forEach(function(d){d.classList.add(h("brace-selected"))})}
if("undefined"!=typeof Prism&&"undefined"!=typeof document){var a={"(":")","[":"]","{":"}"},c={"(":"brace-round","[":"brace-square","{":"brace-curly"},e={"${":"{"},m=0,p=/^(pair-\d+-)(close|open)$/;Prism.hooks.add("complete",function(d){d=d.element;var v=d.parentElement;if(v&&"PRE"==v.tagName){var g=[];if(Prism.util.isActive(d,"match-braces")&&g.push("(","[","{"),0!=g.length){v.__listenerAdded||(v.addEventListener("mousedown",function(){var q=v.querySelector("code"),u=h("brace-selected");Array.prototype.slice.call(q.querySelectorAll("."+
u)).forEach(function(w){w.classList.remove(u)})}),Object.defineProperty(v,"__listenerAdded",{value:!0}));var n=Array.prototype.slice.call(d.querySelectorAll("span."+h("token")+"."+h("punctuation"))),t=[];g.forEach(function(q){for(var u=a[q],w=h(c[q]),A=[],x=[],y=0;y<n.length;y++){var z=n[y];if(0==z.childElementCount){var D=z.textContent;(D=e[D]||D)===q?(t.push({index:y,open:!0,element:z}),z.classList.add(w),z.classList.add(h("brace-open")),x.push(y)):D===u&&(t.push({index:y,open:!1,element:z}),z.classList.add(w),
z.classList.add(h("brace-close")),x.length&&A.push([y,x.pop()]))}}A.forEach(function(G){var J="pair-"+m++ +"-",B=n[G[0]];G=n[G[1]];B.id=J+"open";G.id=J+"close";[B,G].forEach(function(E){E.addEventListener("mouseenter",l);E.addEventListener("mouseleave",f);E.addEventListener("click",b)})})});var k=0;t.sort(function(q,u){return q.index-u.index});t.forEach(function(q){q.open?(q.element.classList.add(h("brace-level-"+(k%12+1))),k++):(k=Math.max(0,k-1),q.element.classList.add(h("brace-level-"+(k%12+1))))})}}})}}();
!function(){function h(a){for(var c=0,e=f.length;c<e;c++)if(!f[c](a))return!1;return!0}if("undefined"!=typeof Prism&&"undefined"!=typeof document){Element.prototype.matches||(Element.prototype.matches=Element.prototype.msMatchesSelector||Element.prototype.webkitMatchesSelector);var r,l=Prism.util.currentScript(),f=[],b=Prism.plugins.filterHighlightAll={add:function(a){f.push(function(c){return a({element:c,language:Prism.util.getLanguage(c)})})},addSelector:function(a){f.push(function(c){return c.matches(a)})},
reject:{add:function(a){f.push(function(c){return!a({element:c,language:Prism.util.getLanguage(c)})})},addSelector:function(a){f.push(function(c){return!c.matches(a)})}},filterKnown:!!l&&l.hasAttribute("data-filter-known")};b.add(function(a){return!b.filterKnown||"object"==typeof Prism.languages[a.language]});l&&((r=l.getAttribute("data-filter-selector"))&&b.addSelector(r),(r=l.getAttribute("data-reject-selector"))&&b.reject.addSelector(r));Prism.hooks.add("before-all-elements-highlight",function(a){a.elements=
a.elements.filter(h)})}}();
"undefined"!=typeof Prism&&(Prism.languages.treeview={"treeview-part":{pattern:/^.+/m,inside:{"entry-line":[{pattern:/\|-- |\u251c\u2500\u2500 /,alias:"line-h"},{pattern:/\| {3}|\u2502 {3}/,alias:"line-v"},{pattern:/`-- |\u2514\u2500\u2500 /,alias:"line-v-last"},{pattern:/ {4}/,alias:"line-v-gap"}],"entry-name":{pattern:/.*\S.*/,inside:{operator:/ -> /}}}}},Prism.hooks.add("wrap",function(h){if("treeview"===h.language&&"entry-name"===h.type){var r=h.classes,l=/(^|[^\\])\/\s*$/;if(l.test(h.content))h.content=
h.content.replace(l,"$1"),r.push("dir");else for(h.content=h.content.replace(/(^|[^\\])[=*|]\s*$/,"$1"),l=h.content.toLowerCase().replace(/\s+/g,"").split(".");l.length>1;)l.shift(),r.push("ext-"+l.join("-"));"."===h.content[0]&&r.push("dotfile")}}));