// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DebugListDirectory() {
  return window['go']['main']['App']['DebugListDirectory']();
}

export function GetIconName(arg1) {
  return window['go']['main']['App']['GetIconName'](arg1);
}

export function GetSvgContent(arg1) {
  return window['go']['main']['App']['GetSvgContent'](arg1);
}

export function GetSvgFiles() {
  return window['go']['main']['App']['GetSvgFiles']();
}
