// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DebugListDirectory():Promise<string>;

export function GetIconName(arg1:string):Promise<string>;

export function GetSvgContent(arg1:string):Promise<string>;

export function GetSvgFiles():Promise<Array<string>>;
